### ISSUE TITLE
plugin did not activate

### ISSUE THREAD

**Issue by mojtaba82** [EssentialBlocks/image-gallery-block#4]
plugin did not activate and make error

Fatal error: Uncaught Error: Failed opening required '/srv/http/wp-content/plugins/image-gallery-block/lib/style-handler/style-handler.php' (include_path='.:') in /srv/http/wp-content/plugins/image-gallery-block/image-gallery-block.php:27 Stack trace: #0 /srv/http/wp-admin/includes/plugin.php(2313): include_once() #1 /srv/http/wp-admin/plugins.php(192): plugin_sandbox_scrape() #2 {main} thrown in /srv/http/wp-content/plugins/image-gallery-block/image-gallery-block.php on line 27

**Comment by fencermonir** [comment]
Hi, @mojtaba82 We have released a new version and fixed the issue. Please check and let us know an update.
